# Generated by Django 5.2.14 on 2026-05-15 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('problem_text', models.TextField(blank=True)),
                ('solution', models.TextField()),
                ('domain', models.CharField(choices=[('calculus', 'Calculus'), ('probability', 'Probability'), ('discrete', 'Discrete'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('ocr_engine', models.CharField(choices=[('tesseract', 'Tesseract'), ('paddle', 'PaddleOCR'), ('none', 'None')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
