# Generated by Django 5.2.17 on 2026-09-21 15:15

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('solver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvehistory',
            name='ocr_engine',
            field=models.CharField(choices=[('tesseract', 'Tesseract'), ('paddle', 'PaddleOCR'), ('easyocr', 'EasyOCR'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='solvehistory',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='solver.conversation'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='solver.conversation')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('input_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='solver.message')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=100)),
                ('predicted_label', models.CharField(max_length=20)),
                ('scores', models.JSONField(default=dict)),
                ('uncertain', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.modelversion')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='solver.problem')),
            ],
        ),
        migrations.CreateModel(
            name='SolveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='message_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['user', 'assistant'])), name='message_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.NegatedExpression(django.db.models.lookups.Exact(django.db.models.functions.text.Trim('content'), models.Value(''))), name='message_nonempty_content'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(condition=models.Q(('input_type__in', ['text', 'image', 'pdf'])), name='problem_valid_input_type'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.NegatedExpression(django.db.models.lookups.Exact(django.db.models.functions.text.Trim('text'), models.Value(''))), name='problem_nonempty_text'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(('predicted_label__in', ['CALCULUS', 'PROBABILITY', 'DISCRETE', 'UNKNOWN'])), name='classification_valid_label'),
        ),
        migrations.AddConstraint(
            model_name='solveevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['succeeded', 'failed'])), name='solve_event_valid_status'),
        ),
    ]
