# Generated by Django 6.1.1 on 2026-09-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_alter_solvehistory_ocr_engine_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solveevent',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solveevent',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solveevent',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solveevent',
            name='provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='solveevent',
            name='reasoning_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
