# Generated by Django 5.2.17 on 2026-09-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_solveevent_input_tokens_solveevent_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='busy_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='lease',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='memory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='reference_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='reference_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solveevent',
            name='cached_input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
